In [4]:
import numpy as np
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
arr[:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9]


In [13]:
arr[(:,:3)]

SyntaxError: invalid syntax (2455410089.py, line 1)

In [14]:
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Extract all rows of the first 3 columns
result = my_array[:, :3]

# Print the result
print(result)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [21]:
np.array_1=[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]

In [26]:
original_array = np.array([[1, 2, 3, 4, 5],
                           [6, 7, 8, 9, 10],
                           [11, 12, 13, 14, 15],
                           [16, 17, 18, 19, 20]])

# Extract the first and third elements from each row
result_array = original_array[:,[0, 2]]

# Print the result
print(result_array)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr.shape

(10,)

In [5]:
arr1=arr.reshape(2,5)
print(arr1)

[[100 100 100 100 100]
 [  5   6   7   8   9]]


In [6]:
arr2=np.zeros((2,3))

In [7]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr3=np.eye(3,3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
arr1

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [10]:
a1=np.empty_like(arr1)
a1

array([[  4128860,   6029375,   3801155,   5570652,   6619251],
       [  7536754,  15794176, 889258339,  23265524,  15742209]])

In [11]:
a2=np.ones_like(arr1)
a2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
a3=np.zeros_like(arr1)
a3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
a4=np.full_like(arr1,100)
a4

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [14]:
arr1

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [15]:
arr1[0,1:3]

array([100, 100])

In [16]:
arr1[1,2:4]

array([7, 8])

In [17]:
arr1[0,3:]

array([100, 100])

In [18]:
arr1[0,-2:]

array([100, 100])

In [19]:
arr1[0,0:]

array([100, 100, 100, 100, 100])

In [20]:
arr1[1,0:]

array([5, 6, 7, 8, 9])

In [21]:
arr1[0:2,2:3]

array([[100],
       [  7]])

In [22]:
arr1[0:2,2]

array([100,   7])

In [23]:
arr1[0:1,2]

array([100])

In [24]:
a1=np.asarray(['sayali','swetha','nida'])
a1.dtype

dtype('<U6')

In [25]:
l=[3,5,8,9]
a2=np.asarray(l)
print(a2)
print(type(a2))

[3 5 8 9]
<class 'numpy.ndarray'>


In [26]:
a3=np.asarray(l)
print(type(a3))

<class 'numpy.ndarray'>


In [27]:
a4=np.array(arr1)
a4_as=np.asarray(arr1)
print(type(a4))
print(type(a4_as))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [28]:
arr1

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [29]:
arr1[0,0]=100

In [30]:
a4

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [31]:
a4_as

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [32]:
a2

array([3, 5, 8, 9])

In [33]:
l

[3, 5, 8, 9]

In [34]:
l[0]=1

In [35]:
l

[1, 5, 8, 9]

In [36]:
a2

array([3, 5, 8, 9])

In [37]:
a6=arr1.copy()

In [38]:
a6

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [39]:
a6

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [40]:
a7=arr1.view()
a7

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [41]:
arr1[0,0]=78

In [42]:
a6

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [43]:
a7

array([[ 78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [44]:
if 78 in a6:
    print('Present')
else:
    print('Absent')

Absent


In [45]:
a6.shape

(2, 5)

In [46]:
a6.shape[0] #no of rows

2

In [47]:
a6.shape[1] #no of columns

5

In [48]:
for i in range(0,a6.shape[0]):
    for j in range(0,a6.shape[1]):
        if a6[i,j]==7:
            print('row',i+1,'col',j+1)

row 2 col 3


In [49]:
a6

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [50]:
arr1

array([[ 78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [51]:
a7=np.concatenate((a6,arr1))
a7

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [52]:
a8=np.concatenate((a6,arr1),axis=1)
a8

array([[100, 100, 100, 100, 100,  78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9,   5,   6,   7,   8,   9]])

In [53]:
a7.shape

(4, 5)

In [54]:
a8.shape

(2, 10)

In [55]:
arr2=np.ones_like(arr)

In [56]:
arr2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [57]:
arr3=np.full_like(arr,100)

In [58]:
arr3

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr4=arr.reshape(2,5)

In [60]:
arr4

array([[ 78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [61]:
arr4[0,1:3]

array([100, 100])

In [62]:
arr4[1,2:4]

array([7, 8])

In [63]:
arr4[0,3:5]

array([100, 100])

In [64]:
arr4[0:2,2:3]

array([[100],
       [  7]])

In [65]:
arr4[0:2,2]

array([100,   7])

In [66]:
arr4[0:1,3:5]

array([[100, 100]])

In [67]:
arr

array([ 78, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [68]:
arr1

array([[ 78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [69]:
arr4

array([[ 78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [70]:
a1=np.array(arr4)

In [71]:
a1

array([[ 78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [72]:
a1_as=np.asarray(arr4)

In [73]:
a1_as

array([[ 78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [74]:
arr4[0,0]=100

In [75]:
arr4

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [76]:
a1

array([[ 78, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [77]:
a1_as

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [78]:
a1_as.dtype

dtype('int32')

In [79]:
arr4

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [80]:
for i in range(0,arr4.shape[0]):
    for j in range(0,arr4.shape[1]):
        if arr4[i,j]==7:
            print(i+1,j+1)

2 3


In [81]:
import pandas as pd

In [82]:
df=pd.read_csv('E:\Data Science\Datasets\survey_lung_cancer.csv')

In [83]:
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [84]:
df.tail()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
304         2                    2                      2           1   
305         2                    2                      1           2   
306         2                    1                      1           2   
307         2                    2                      1           2   
308         1                    1                      2           1   

    LUNG_CANCER  
304         YES  
305         YES  
306         YES  
307         YES  
308         YES

In [85]:
df.shape

(309, 16)

In [86]:
df.head(10)

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   
5      F   75        1               2        1              1   
6      M   52        2               1        1              1   
7      F   51        2               2        2              2   
8      F   68        2               1        2              1   
9      M   53        2               2        2              2   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   
5                2         2         2         2                  1         2   
6                1         2         1         2                  2         2   
7                1         2         2         1                  1         1   
8                1         2         1         1                  1         1   
9                2         1         2         1                  2         1   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO  
5                    2                      1           1         YES  
6                    2                      1           2         YES  
7                    2                      2           1         YES  
8                    1                      1           1          NO  
9                    1                      2           2         YES

In [87]:
arr4

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [88]:
np.average(arr4)

53.5

In [89]:
ary=np.array([5,2,8,9,7])
ary=ary+1
print(ary)

[ 6  3  9 10  8]


In [90]:
price=[898, 28, 377, 782, 80, 338, 122, 553, 178, 387, 582, 321, 561, 421, 163, 857, 254, 616, 778, 791, 25, 559, 282, 380, 429, 226, 151, 209, 281, 20, 517, 62, 316, 55, 541, 287, 815, 855, 590, 433, 226, 694, 150, 615, 440, 515, 264, 621, 676, 722, 769, 811, 190, 881, 307, 119, 200, 572, 403, 898, 398, 473, 663, 299, 65, 697, 611, 527, 682, 582, 465, 739, 513, 688, 190, 406, 231, 606, 87, 203, 859, 396, 322, 303, 342, 110, 270, 306, 674, 733, 273, 234, 573, 436, 445, 734, 53, 745, 881, 98, 745, 266, 605, 680, 809, 138, 33, 825, 84, 413, 229, 183, 25, 653, 780, 741, 685, 533, 844, 450, 692, 573, 403, 645, 511, 150, 218, 724, 318, 689, 515, 850, 859, 225, 776, 112, 696, 730, 260, 26, 542, 824, 81, 889, 137, 535, 546, 261, 620, 549, 92, 891, 438, 749, 861, 535, 60, 661, 311, 527, 20, 544, 196, 557, 166, 248, 95, 737, 658, 335, 146, 845, 363, 879, 309, 52, 564, 33, 277, 40, 336, 852]

In [91]:
np.average(price)

451.4230769230769

In [92]:
sorts=np.sort(np.array(price))

In [93]:
sorts

array([ 20,  20,  25,  25,  26,  28,  33,  33,  40,  52,  53,  55,  60,
        62,  65,  80,  81,  84,  87,  92,  95,  98, 110, 112, 119, 122,
       137, 138, 146, 150, 150, 151, 163, 166, 178, 183, 190, 190, 196,
       200, 203, 209, 218, 225, 226, 226, 229, 231, 234, 248, 254, 260,
       261, 264, 266, 270, 273, 277, 281, 282, 287, 299, 303, 306, 307,
       309, 311, 316, 318, 321, 322, 335, 336, 338, 342, 363, 377, 380,
       387, 396, 398, 403, 403, 406, 413, 421, 429, 433, 436, 438, 440,
       445, 450, 465, 473, 511, 513, 515, 515, 517, 527, 527, 533, 535,
       535, 541, 542, 544, 546, 549, 553, 557, 559, 561, 564, 572, 573,
       573, 582, 582, 590, 605, 606, 611, 615, 616, 620, 621, 645, 653,
       658, 661, 663, 674, 676, 680, 682, 685, 688, 689, 692, 694, 696,
       697, 722, 724, 730, 733, 734, 737, 739, 741, 745, 745, 749, 769,
       776, 778, 780, 782, 791, 809, 811, 815, 824, 825, 844, 845, 850,
       852, 855, 857, 859, 859, 861, 879, 881, 881, 889, 891, 89

In [94]:
df

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0        M   69        1               2        2              1   
1        M   74        2               1        1              1   
2        F   59        1               1        1              2   
3        M   63        2               2        2              1   
4        F   63        1               2        1              1   
..     ...  ...      ...             ...      ...            ...   
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2         2         2         1                  1   
2                  1         2         1         2                  1   
3                  1         1         1         1                  2   
4                  1         1         1         2                  1   
..               ...       ...       ...       ...                ...   
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
0           2                    2                      2           2   
1           1                    2                      2           2   
2           2                    2                      1           2   
3           1                    1                      2           2   
4           2                    2                      1           1   
..        ...                  ...                    ...         ...   
304         2                    2                      2           1   
305         2                    2                      1           2   
306         2                    1                      1           2   
307         2                    2                      1           2   
308         1                    1                      2           1   

    LUNG_CANCER  
0           YES  
1           YES  
2            NO  
3            NO  
4            NO  
..          ...  
304         YES  
305         YES  
306         YES  
307         YES  
308         YES  

[309 rows x 16 columns]

In [96]:
df['AGE'].unique()

array([69, 74, 59, 63, 75, 52, 51, 68, 53, 61, 72, 60, 58, 48, 57, 44, 64,
       21, 65, 55, 62, 56, 67, 77, 70, 54, 49, 73, 47, 71, 66, 76, 78, 81,
       79, 38, 39, 87, 46], dtype=int64)

In [99]:
df.groupby('GENDER')['SMOKING','ANXIETY'].sum()

C:\Users\Prem\AppData\Local\Temp\ipykernel_12828\466040464.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby('GENDER')['SMOKING','ANXIETY'].sum()


SMOKING  ANXIETY
GENDER                  
F           227      232
M           256      231

In [103]:
df.loc[2,'AGE']

59

In [108]:
df.iloc[:4,1:]

AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC DISEASE  \
0   69        1               2        2              1                1   
1   74        2               1        1              1                2   
2   59        1               1        1              2                1   
3   63        2               2        2              1                1   

   FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0         2         1         2                  2         2   
1         2         2         1                  1         1   
2         2         1         2                  1         2   
3         1         1         1                  2         1   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO

In [109]:
df.columns

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'LUNG_CANCER'],
      dtype='object')