In [1]:
import time
python_list=list(range(1000000))
start_time=time.time()
sq_items=[x**2 for x in python_list]
time.time()-start_time

0.13167500495910645

In [2]:
import numpy as np
start_time=time.time()
numpy_array=np.array(python_list)
sq_var=numpy_array**2
time.time()-start_time

0.13666152954101562

In [3]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
np.array([[1,2,3,4],[1,2,3,4]]).ndim

2

In [6]:
np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]).ndim

3

In [7]:
len(np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]))

1

In [8]:
len(np.array([[1,2,3,4],[1,2,3,4]]))

2

In [9]:
len(np.array([1,2,3,4]))

4

In [10]:
np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [11]:
np.array([[1,2,3,4],[1,2,3,4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [13]:
arr=np.array([1,2,3,4],int)
print(arr.dtype)

int32


In [14]:
import sys

is_64bits = sys.maxsize > 2**32
print(is_64bits)

if is_64bits:
    print('Python is running as 64-bit application')
else:
    print('Python is running as 32-bit application')

True
Python is running as 64-bit application


In [15]:
import struct
print(struct.calcsize("P") * 8)

64


In [16]:
arr=np.linspace(0,15)
print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [17]:
lst=[1,2,3,4,5]
print(lst[:4])

[1, 2, 3, 4]


In [18]:
print(lst[3:])

[4, 5]
