### BroadCasting

#### Array + Scaler

In [1]:
import numpy as np
a = np.array([14, 12, 49]) # 1x3 Dimension array
print(a)
b = 4
print(b)
 
# Broadcasting happened because of
# miss match in array Dimension.
c = a + b
print(c)

[14 12 49]
4
[18 16 53]


#### Array + Array

In [2]:
import numpy as np
 
v = np.array([[12, 24, 36,36],[15,46,34,34]]) 
w = np.array([45,45,45,45]) 

v+w

array([[57, 69, 81, 81],
       [60, 91, 79, 79]])

# Mathematical Operations

In [3]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [4]:
x

array([[1, 2],
       [3, 4]])

In [5]:
y

array([[5, 6],
       [7, 8]])

In [6]:
## Addition (Element-wise addition)

In [7]:
x+y

array([[ 6,  8],
       [10, 12]])

In [8]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [9]:
## Substraction (Element-wise Substraction)

In [10]:
x-y

array([[-4, -4],
       [-4, -4]])

In [11]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [12]:
## Division (Element-wise Division)

In [13]:
x

array([[1, 2],
       [3, 4]])

In [14]:
y

array([[5, 6],
       [7, 8]])

In [15]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [16]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [17]:
# Element Wise Multiplication

In [18]:
x*y

array([[ 5, 12],
       [21, 32]])

In [19]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [20]:
## Matrix Multiplication

In [21]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [22]:
x@y
## @ this is used to do dot product

array([[19, 22],
       [43, 50]])

## Comparator Operators

In [115]:
arr1=np.array([1,2,3,4])
arr2=np.array([8,5,3,4])
arr1==arr2

array([False, False,  True,  True])

In [116]:
arr1>arr2

array([False, False, False, False])

In [118]:
arr1<arr2

array([ True,  True, False, False])

### Statistical Operations

In [23]:
w=[60, 59, 71, 80, 48, 39, 73, 72, 74, 83, 73, 35, 87, 69, 62, 47, 59, 35, 68, 64, 78, 68, 40, 71, 65, 63, 36, 40, 37, 49]
weight=np.array(w)

In [24]:
np.min(weight)

35

In [25]:
np.max(weight)

87

In [26]:
np.mean(weight)

60.166666666666664

In [27]:
np.var(weight)

239.8722222222222

In [29]:
np.std(weight)

15.48780882572555

In [30]:
np.sum(weight)

1805

In [31]:
np.cumsum(weight)

array([  60,  119,  190,  270,  318,  357,  430,  502,  576,  659,  732,
        767,  854,  923,  985, 1032, 1091, 1126, 1194, 1258, 1336, 1404,
       1444, 1515, 1580, 1643, 1679, 1719, 1756, 1805])

### Poll question 1-

Ques. Find the median for the given array of weights.

- (a) 63
- (b) 63.5
- (c) 67
- (d) 69

## Reshape Function

In [32]:
arr=np.arange(0,10)
reshaped_arr=arr.reshape(2,5)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
arr.size

10

In [36]:
reshaped_arr.size

10

In [37]:
arr=np.arange(0,20)#20

In [38]:
arr1=arr.reshape(5,4)

In [39]:
arr1.shape

(5, 4)

In [40]:
arr.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [41]:
arr=np.arange(0,21)
arr.reshape(7,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

## Transpose

In [42]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
arr1.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [44]:
np.transpose(arr1)

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

# Stacking

In [46]:
x

array([[1, 2],
       [3, 4]])

In [47]:
y

array([[5, 6],
       [7, 8]])

In [48]:
np.vstack((x,y))#top and bottom (No. of columns has to be same)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
np.hstack((x,y))#side by side (Number of rows has to be same, columns does not matter)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Poll question 2-

Ques. What will be output of following code.

print(np.arange(100,300,4).reshape(5,10).T.shape[0])

- (a) 10
- (b) 5
- (c) 100
- (d) 4

### Sorting

In [102]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Flatten

In [104]:
arr = np.array([[5, 6], [7, 8]])
  
arr1 = arr.flatten()
  
print( arr1 )

[5 6 7 8]


### Unravel Index

In [105]:
gfg = np.unravel_index([22, 41, 37], (7, 6))
  
print(gfg)

(array([3, 6, 6]), array([4, 5, 1]))


### ravel and unravel

In [109]:
array = np.arange(15).reshape(3, 5)
print("Original array : \n", array)
 
# Output comes like [ 0  1  2 ..., 12 13 14]
# as it is a long output, so it is the way of
# showing output in Python
print("\nravel() : ", array.ravel())

Original array : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

ravel() :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### Pandas

In [60]:
import pandas as pd
#pip install pandas

- Series as generalized NumPy array<br>
**The essential difference is the presence of the index: while the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values.*

In [62]:
s1 = pd.Series(1)
s1

0    1
dtype: int64

In [111]:
arr,s1

(array([[5, 6],
        [7, 8]]),
 0    1
 dtype: int64)

In [64]:
# create from list
s2 = pd.Series([10,21,34,41,59])
s2

0    10
1    21
2    34
3    41
4    59
dtype: int64

In [65]:
s3 = pd.Series([1,2,3], index=['a','b','c'])
s3

a    1
b    2
c    3
dtype: int64

In [66]:
s4 = pd.Series([2,1,1], index=['India','Pakistan','SriLanka'])
s4

India       2
Pakistan    1
SriLanka    1
dtype: int64

In [67]:
s4.index

Index(['India', 'Pakistan', 'SriLanka'], dtype='object')

In [68]:
s4.values

array([2, 1, 1])

In [106]:
dictionary = {'A' : 10, 'B' : 20, 'C' : 30}
  
# create a series
series = pd.Series(dictionary)
  
print(series)

A    10
B    20
C    30
dtype: int64


### Accessing the Value

In [69]:
s4["India"]

2

### Add, update and delete Operations

In [83]:
s5=s4.append(pd.Series(2,index=["England"]))
s5

India       2
Pakistan    1
SriLanka    1
England     2
dtype: int64

In [84]:
del s5["England"]

In [85]:
s5

India       2
Pakistan    1
SriLanka    1
dtype: int64

In [86]:
s4.update(pd.Series(2,index=["Pakistan"]))

In [87]:
s4

India       2
Pakistan    2
SriLanka    1
dtype: int64

### Poll question 3-

Ques. What will be output of following code.<br>
s4=pd.Series([1,2,4,3], index=['Python','R','C','C++'])<br>
s4.append(pd.Series(5,index=["Java"])).update(pd.Series(3,index=["Java"]))<br>
print(s4["Java"])


- (a) 5
- (b) 3
- (c) 1
- (d) 0

In [101]:
s4=pd.Series([1,2,4,3], index=['Python','R','C','C++'])
s4=s4.append(pd.Series(5,index=["Java"]))
s4.update(pd.Series(3,index=["Java"]))
print(s4["Java"])

3
