In [1]:
import pandas as pd
import numpy as np

In [3]:
# Create an (8, 8) shape NumPy array
array = np.arange(64).reshape(8, 8)
print(array)
# Find the index (x, y) of the 50th element
element_number = 50
x, y = np.where(array == element_number)

# Print the index
print("Index (x, y) of element", element_number, "is:", (x[0], y[0]))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
Index (x, y) of element 50 is: (6, 2)


In [4]:
ar2=np.arange(36).reshape(6,6)
print(ar2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [7]:
ar2[:3,-5:]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17]])

In [8]:
ar3=np.arange(1,16,2).reshape(4, 2)
ar3

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [10]:
ar4=np.arange(1,16,2)
ar4

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [11]:
n = 5  # You can change the value of 'n' as needed

if n > 2 and n % 2 != 0:
    # Create an (n x n) array of zeros
    arr = np.zeros((n, n), dtype=int)

    # Fill the middle row and middle column with ones
    middle = n // 2
    arr[middle, :] = 1  # Fill the middle row with ones
    arr[:, middle] = 1  # Fill the middle column with ones

    # Print the resulting array
    print(arr)
else:
    print("Input 'n' must be a positive odd integer greater than 2.")

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [13]:
6//2

3