In [1]:
import numpy as np
import time
import sys

In [2]:
l=range(1000)
print(sys.getsizeof(1)*len(l))

28000


In [3]:
arr=np.arange(1000)
print(arr.size*arr.itemsize)

4000


In [4]:
size=1000000
l1=range(size)
l2=range(size)

In [5]:
a1=np.arange(size)
a2=np.arange(size)

In [6]:
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print('list took:', (time.time()-start)*1000)

start=time.time()
result=a1+a2
print('numpy took:',(time.time()-start)*1000)

list took: 117.0806884765625
numpy took: 18.152713775634766


In [16]:
a=np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [8]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [13]:
a.dtype

dtype('int8')

In [14]:
b.dtype

dtype('float64')

In [17]:
a.itemsize

2